version: 2
jobs:
  build:
    docker:
#      - image: quay.io/3scale/s2i-openresty-centos7:luarocks-build
       - image: jfernandes/circleci-node-lua:v1.0.0
    steps:
      - checkout
      - run: 
          name: test and save results
          command: |
            mkdir -p ~/test-results/junit/
            busted spec -o junit > ~/test-results/junit/results.xml
          when: always
      - store_test_results:
          path: ~/test-results